### ISSUE TITLE
Import the dataset into Jupyter Notebook

### ISSUE THREAD

**Issue by sakshamv30** [sakshamv30/GetSetFOSS_ML#1]
The first step to import the dataset is to first import the getsetfoss_pandas.ipynb file in your local system.
For that you need to download the Jupyter Software from the internet itself.
The Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and explanatory text.

**Comment by 3762bhanu** [comment]
Sir,I want to work on this issue

**Comment by 0Archana** [comment]
I want to claim this issue

**Comment by sus5pect** [comment]
I want to do this

**Comment by sakshamv30** [comment]
This issue is open for everyone.

**Comment by vect-0r** [comment]
I have imported the getsetfoss_pandas.ipynb file in my local system. But how do I show here that I have done it?

**Comment by vect-0r** [comment]
@sakshamv30 I opened a pull request regarding this issue. Please review it.

**Comment by sakshamv30** [comment]
It's not what is asked. You have to import the dataset zoo.csv in your jupyter notebook, writing a code snippet for the same. @RoopamJain00  then submit the updated jupyter notebook.

**Comment by ghost** [comment]
@sakshamv30  how do i upload screenshot of  issue that i have solved

**Comment by sakshamv30** [comment]
Edit in the .ipynb file itself and push that changed file on your forked repo. and create a pull request for the same. @3762bhanu

**Comment by sakshamv30** [comment]
Changed the label from Easy to Medium. Also, complete all the code snippet in the ipynb file.
