### ISSUE TITLE
Find all the numbers greater than 89

### ISSUE THREAD

**Issue by sa4k5hi** [sakshamv30/GetSetFOSS_ML#5]
Find all the numbers greater than 89 and print them in the array named "numbers_" using boolean array indexing.

**Comment by archana-17** [comment]
I want to claim this issue

**Comment by sakshamv30** [comment]
This is issue is assigned for 2 days to @0pichu

**Comment by sakshamv30** [comment]
@0pichu will be removed as a assignee by evening 6pm.

**Comment by arhum602** [comment]
I want to claim this issue after @0pichu

**Comment by sakshamv30** [comment]
The deadline for submission is today till 6pm

**Comment by arhum602** [comment]
I have done it

**Comment by Mohit9487** [comment]
i want to claim this issue
