### ISSUE TITLE
Some basic Array things

### ISSUE THREAD

**Issue by sa4k5hi** [sakshamv30/GetSetFOSS_ML#6]
Find the dimension, size and datatype of the array named "numbers_"

**Comment by sus5pect** [comment]
I want to do this

**Comment by sa4k5hi** [comment]
This issue is for everyone

**Comment by yadavashu** [comment]
@sa4k5hi where is the file related to this array?

**Comment by sa4k5hi** [comment]
Go to numpy folder and there you will find the jupyter notebook, at the end of the notebook it is mentioned
